// packages/app/src/components/popover.tsx
import {
  type FloatingContext,
  FloatingPortal,
  type Placement,
  arrow,
  autoUpdate,
  flip,
  offset,
  shift,
  useClick,
  useDismiss,
  useFloating,
  useId,
  useInteractions,
} from "@floating-ui/react";
import { TransitionV2 as Transition } from "@hiogawa/tiny-transition/dist/react";
import React from "react";
import { cls } from "../utils/misc";

interface PopoverRenderProps {
  open: boolean;
  setOpen: (open: boolean) => void;
  props: Record<string, unknown>;
  arrowProps?: Record<string, unknown>;
  context: FloatingContext; // context.placement is an actual placement e.g. after `flip` middleware is applied
}

function Popover(props: {
  placement: Placement;
  reference: (renderProps: PopoverRenderProps) => React.ReactNode;
  floating: (renderProps: PopoverRenderProps) => React.ReactNode;
}) {
  const [open, setOpen] = React.useState(false);
  const arrowRef = React.useRef<Element>(null);

  // `floatingStyle` lags a moment and breaks animation?
  const { refs, x, y, strategy, context, middlewareData } = useFloating({
    open,
    onOpenChange: setOpen,
    placement: props.placement,
    middleware: [
      offset(17),
      flip(),
      shift(),
      arrow({ element: arrowRef, padding: 10 }),
    ],
    whileElementsMounted: autoUpdate,
  });

  const { getReferenceProps, getFloatingProps } = useInteractions([
    useClick(context),
    useDismiss(context),
  ]);

  const id = useId();

  return (
    <>
      {props.reference({
        open,
        setOpen,
        props: getReferenceProps({
          ref: refs.setReference,
        }),
        context,
      })}
      <FloatingPortal id={id}>
        {props.floating({
          open,
          setOpen,
          props: getFloatingProps({
            ref: refs.setFloating,
            style: {
              top: y ?? "",
              left: x ?? "",
              position: strategy,
            },
          }),
          arrowProps: {
            ref: arrowRef,
            style: {
              top: middlewareData.arrow?.y ?? "",
              left: middlewareData.arrow?.x ?? "",
              position: "absolute",
            },
          },
          context,
        })}
      </FloatingPortal>
    </>
  );
}

//
// simple wrapper with transition
//

// https://ant.design/components/popover
export function PopoverSimple({
  placement,
  reference,
  floating,
}: {
  placement: Placement;
  reference: MaybeCallable<React.ReactElement, [FloatingContext]>;
  floating: MaybeCallable<React.ReactElement, [FloatingContext]>;
}) {
  return (
    <Popover
      placement={placement}
      reference={({ props, context }) =>
        React.cloneElement(maybeCall(reference, [context]), props)
      }
      floating={({ props, open, arrowProps, context }) => (
        <Transition
          show={open}
          className="transition duration-150"
          enterFrom="scale-80 opacity-0"
          enterTo="scale-100 opacity-100"
          leaveFrom="scale-100 opacity-100"
          leaveTo="scale-80 opacity-0"
          {...props}
        >
          <div className="antd-floating">
            {arrowProps && (
              <Arrow placement={context.placement} arrowProps={arrowProps} />
            )}
            {maybeCall(floating, [context])}
          </div>
        </Transition>
      )}
    />
  );
}

// `FloatingArrow` from @floating-ui/react is not used since the shadow didn't look right.
function Arrow({
  arrowProps,
  placement,
}: {
  arrowProps: {}; // cheat forwarded ref
  placement: Placement;
}) {
  return (
    <div
      {...arrowProps}
      className={cls(
        placement.startsWith("bottom") && "top-0",
        placement.startsWith("top") && "bottom-0",
        placement.startsWith("left") && "right-0",
        placement.startsWith("right") && "left-0"
      )}
    >
      <div
        // rotate 4x4 square with shadow
        className={cls(
          "antd-floating !shadow-[var(--antd-boxShadowPopoverArrow)] relative w-4 h-4",
          placement.startsWith("bottom") && "-top-2 rotate-[225deg]",
          placement.startsWith("top") && "-bottom-2 rotate-[45deg]",
          placement.startsWith("left") && "-right-2 rotate-[315deg]",
          placement.startsWith("right") && "-left-2 rotate-[135deg]"
        )}
        // clip half
        style={{
          clipPath: "polygon(100% 0%, 200% 100%, 100% 200%, 0% 100%)",
        }}
      />
    </div>
  );
}

//
// misc
//

type MaybeCallable<T, Args extends any[]> = T | ((...args: Args) => T);

function maybeCall<T, Args extends any[]>(
  f: MaybeCallable<T, Args>,
  args: Args
): T {
  return typeof f === "function" ? (f as any)(...args) : f;
}

// packages/app-solid/src/components/popover.tsx
import {
  ComputePositionConfig,
  ComputePositionReturn,
  Middleware,
  MiddlewareData,
  Placement,
  arrow,
  autoUpdate,
  computePosition,
  flip,
  offset,
  shift,
} from "@floating-ui/dom";
import { mapOption, tinyassert } from "@hiogawa/utils";
import { Ref } from "@solid-primitives/refs";
import {
  Accessor,
  JSX,
  Setter,
  createEffect,
  createMemo,
  createSignal,
  onCleanup,
  untrack,
} from "solid-js";
import { Portal } from "solid-js/web";
import { cls, onDocumentEvent } from "./utils";

type FloatingContext = {
  open: Accessor<boolean>;
  setOpen: Setter<boolean>;
  reference: Accessor<HTMLElement | undefined>;
  floating: Accessor<HTMLElement | undefined>;
  floatingStyle: Accessor<JSX.CSSProperties | undefined>;
  placement: Accessor<Placement | undefined>; // actual placement e.g. after layout by flip middleware
  middlewareData: Accessor<MiddlewareData | undefined>;
};

type ArrowContext = {
  ref: Setter<HTMLElement | undefined>;
  style: Accessor<JSX.CSSProperties>;
};

export function Popover(props: {
  placement: Placement;
  reference: (arg: { ctx: FloatingContext }) => JSX.Element;
  floating: (arg: {
    ctx: FloatingContext;
    arrowCtx: ArrowContext;
  }) => JSX.Element;
}) {
  const [referenceRef, setReferenceRef] = createSignal<HTMLElement>();
  const [floatingRef, setFloatingRef] = createSignal<HTMLElement>();
  const [arrowRef, setArrowRef] = createSignal<HTMLElement>();
  const [open, setOpen] = createSignal(false);

  const ctx = createFloating({
    reference: referenceRef,
    floating: floatingRef,
    open,
    setOpen,
    placement: () => props.placement,
    middleware: () => [
      offset(17),
      flip(),
      shift(),
      arrowLazy({ element: () => untrack(arrowRef), padding: 10 }),
    ],
  });

  createDismissInteraction(ctx);
  createClickInteraction(ctx);

  // further derive for arrow
  const arrowStyle = createMemo<JSX.CSSProperties>(() => ({
    position: "absolute",
    top: mapOption(ctx.middlewareData()?.arrow?.y, (v) => `${v}px`),
    left: mapOption(ctx.middlewareData()?.arrow?.x, (v) => `${v}px`),
  }));

  const arrowCtx: ArrowContext = {
    ref: setArrowRef,
    style: arrowStyle,
  };

  return (
    <>
      <Ref ref={setReferenceRef}>{props.reference({ ctx })}</Ref>
      <Portal>
        <Ref ref={setFloatingRef}>{props.floating({ ctx, arrowCtx })}</Ref>
      </Portal>
    </>
  );
}

export function FloatingArrow(
  props: { placement: Placement } & JSX.HTMLElementTags["div"]
) {
  return (
    <div
      style={props.style}
      class={cls(
        props.placement.startsWith("bottom") && "top-0",
        props.placement.startsWith("top") && "bottom-0",
        props.placement.startsWith("left") && "right-0",
        props.placement.startsWith("right") && "left-0"
      )}
    >
      <div
        // rotate 4x4 square with shadow
        class={cls(
          "antd-floating !shadow-[var(--antd-boxShadowPopoverArrow)] relative w-4 h-4",
          props.placement.startsWith("bottom") && "-top-2 rotate-[225deg]",
          props.placement.startsWith("top") && "-bottom-2 rotate-[45deg]",
          props.placement.startsWith("left") && "-right-2 rotate-[315deg]",
          props.placement.startsWith("right") && "-left-2 rotate-[135deg]"
        )}
        // clip half
        style={{
          "clip-path": "polygon(100% 0%, 200% 100%, 100% 200%, 0% 100%)",
        }}
      />
    </div>
  );
}

function createFloating(props: {
  reference: Accessor<HTMLElement | undefined>;
  floating: Accessor<HTMLElement | undefined>;
  open: Accessor<boolean>;
  setOpen: Setter<boolean>;
  placement: Accessor<ComputePositionConfig["placement"]>;
  middleware: Accessor<ComputePositionConfig["middleware"]>;
}): FloatingContext {
  const [result, setResult] = createSignal<ComputePositionReturn>();

  createEffect(() => {
    const reference = props.reference();
    const floating = props.floating();

    if (!reference || !floating) {
      setResult(undefined);
      return;
    }

    // setup auto update
    const placement = props.placement?.();
    const middleware = props.middleware?.();
    async function update() {
      tinyassert(reference);
      tinyassert(floating);
      const result = await computePosition(reference, floating, {
        placement,
        middleware,
      });
      setResult(result);
    }
    const cleanup = autoUpdate(reference, floating, update);
    onCleanup(() => cleanup());
  });

  return {
    open: props.open,
    setOpen: props.setOpen,
    reference: props.reference,
    floating: props.floating,
    floatingStyle: () => mapOption(result(), getFloatingStyle),
    placement: () => result()?.placement,
    middlewareData: () => result()?.middlewareData,
  };
}

// accept arrow element lazily like react https://github.com/floating-ui/floating-ui/blob/947b4d5aadd59d40f4add43700483818ee55a96f/packages/react-dom/src/arrow.ts#L16
function arrowLazy(options: {
  element?: Accessor<Element | undefined>;
  padding?: number;
}): Middleware {
  return {
    name: "arrow",
    options,
    fn(args) {
      const element = options.element?.();
      if (element) {
        return arrow({ ...options, element }).fn(args);
      }
      return {};
    },
  };
}

function createDismissInteraction(ctx: FloatingContext) {
  // dismiss on click outside
  createEffect(() => {
    const reference = ctx.reference();
    const floating = ctx.floating();

    onDocumentEvent("pointerdown", (e) => {
      if (
        e.target instanceof Node &&
        !reference?.contains(e.target) &&
        !floating?.contains(e.target)
      ) {
        ctx.setOpen(false);
      }
    });
  });

  // dismiss on escape
  onDocumentEvent("keyup", (e) => {
    if (e.key === "Escape") {
      ctx.setOpen(false);
    }
  });
}

function createClickInteraction(ctx: FloatingContext) {
  createEffect(() => {
    const reference = ctx.reference();
    if (reference) {
      function callback() {
        ctx.setOpen((prev) => !prev);
      }
      reference.addEventListener("click", callback);
      onCleanup(() => {
        document.removeEventListener("click", callback);
      });
    }
  });
}

function getFloatingStyle(result: ComputePositionReturn): JSX.CSSProperties {
  return {
    left: `${result.x}px`,
    top: `${result.y}px`,
    position: result.strategy,
  };
}
